from models.course import Course
from models.teachers.subject_specialities import SubjectSpecialty
from models.schools.school import School
from models.students.student import Student
from models.teachers.teacher import Teacher
from models.schools.school_course import SchoolCourse
from models.students.student_course import StudentCourse
from models.students.student_grade import StudentGrade
from models.teachers.teacher_course import TeacherCourse